---
# handlers file for wireguard_add_client
- name: restart wireguard
  ansible.builtin.service:
    name: wg-quick@wg0
    state: restarted

- name: restart dnsmasq
  ansible.builtin.service:
    name: dnsmasq
    state: restarted
  failed_when: false