---
# tasks file for initial_setup hardening
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: yes
    cache_valid_time: 3600
  register: apt_update_result
  until: apt_update_result is successful
  retries: 10
  delay: 10

- name: Install hardening packages
  ansible.builtin.apt:
    name:
      - ufw
      - fail2ban
      - unattended-upgrades
    state: present
  register: apt_install_hardening_result
  until: apt_install_hardening_result is successful
  retries: 10
  delay: 10

- name: Check current SSH port in sshd_config
  ansible.builtin.shell: "grep '^Port' /etc/ssh/sshd_config | awk '{print $2}'"
  register: current_ssh_port_check
  check_mode: no
  changed_when: false
  failed_when: false

- name: Set old_ssh_port fact
  ansible.builtin.set_fact:
    old_ssh_port: "{{ current_ssh_port_check.stdout | default('22', true) | trim }}"

- name: Allow SSH through UFW
  community.general.ufw:
    rule: allow
    port: "{{ ssh_port }}"
    proto: tcp

- name: Remove old SSH port from UFW
  community.general.ufw:
    rule: allow
    port: "{{ old_ssh_port }}"
    proto: tcp
    delete: yes
  when: old_ssh_port | string != ssh_port | string and old_ssh_port | length > 0

- name: Set UFW default policy
  community.general.ufw:
    policy: deny
    direction: incoming

- name: Enable UFW
  community.general.ufw:
    state: enabled

- name: Configure fail2ban jail.local
  ansible.builtin.template:
    src: jail.local.j2
    dest: /etc/fail2ban/jail.local
    mode: '0644'
  notify: restart fail2ban

- name: Ensure fail2ban service is enabled and started
  ansible.builtin.service:
    name: fail2ban
    state: started
    enabled: yes

- name: Configure unattended-upgrades
  ansible.builtin.template:
    src: 50unattended-upgrades.j2
    dest: /etc/apt/apt.conf.d/50unattended-upgrades
    mode: '0644'

- name: Enable unattended-upgrades
  ansible.builtin.copy:
    content: 'APT::Periodic::Update-Package-Lists "1";
APT::Periodic::Unattended-Upgrade "1";'
    dest: /etc/apt/apt.conf.d/20auto-upgrades
    mode: '0644'

- name: Create new user
  ansible.builtin.user:
    name: "{{ new_user }}"
    password: "{{ new_user_password | password_hash('sha512') }}" # Hash the password
    shell: /bin/bash
    groups: sudo
    append: yes
    state: present

- name: Add new user to sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/{{ new_user }}
    create: yes
    mode: '0440'
    line: "{{ new_user }} ALL=(ALL) ALL"
    validate: /usr/sbin/visudo -cf %s

- name: Set authorized key for new user
  ansible.builtin.authorized_key:
    user: "{{ new_user }}"
    state: present
    key: "{{ new_user_ssh_key }}"

- name: Change SSH port
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?Port'
    line: "Port {{ ssh_port }}"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: "PermitRootLogin no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: Disable Challenge Response Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?ChallengeResponseAuthentication'
    line: "ChallengeResponseAuthentication no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd


- name: Disable X11 Forwarding
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?X11Forwarding'
    line: "X11Forwarding no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: Disable Password Authentication
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PasswordAuthentication'
    line: "PasswordAuthentication no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd

- name: Disable Empty Passwords
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#?PermitEmptyPasswords'
    line: "PermitEmptyPasswords no"
    state: present
    validate: /usr/sbin/sshd -t -f %s
  notify: restart sshd
