---
# tasks file for reverse_proxy
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  register: apt_install_nginx_result
  until: apt_install_nginx_result is successful
  retries: 10
  delay: 10

- name: Allow HTTP and HTTPS through UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - http
    - https

- name: Ensure Nginx service is enabled and started
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started

- name: Configure Nginx rate limiting for webhooks
  ansible.builtin.copy:
    dest: /etc/nginx/conf.d/webhook_rate_limit.conf
    content: |
      # Rate limit zone for webhooks
      # 30 requests per minute per IP, with a burst of 10
      limit_req_zone $binary_remote_addr zone=webhook:10m rate=30r/m burst=10;
      limit_req_status 429; # Return 429 Too Many Requests on rate limit exceed
    mode: '0644'
  notify: restart nginx
