---
# tasks file for reverse_proxy
- name: Install Nginx
  ansible.builtin.apt:
    name: nginx
    state: present
  register: apt_install_nginx_result
  until: apt_install_nginx_result is successful
  retries: 10
  delay: 10

- name: Allow HTTP and HTTPS through UFW
  community.general.ufw:
    rule: allow
    port: "{{ item }}"
    proto: tcp
  loop:
    - http
    - https

- name: Ensure Nginx service is enabled and started
  ansible.builtin.systemd:
    name: nginx
    enabled: yes
    state: started
